### ISSUE TITLE
Cracked IP redirect  problem

### ISSUE THREAD

**Issue by EDGECOM666** [maiorBoltach/bf2142stats_emu#5]
I have hexedited   the cracked exec with HxD and the client will only resolve to 192.168.1.3

I can create accounts and play the game if I set the IP on my server to 192.168.1.3

I have changed all instances of 192.168.1.3 to 192.168.1.4 and for fun I also changed it to a dns name and still did not forward to the new IP

![bf2142exe](https://user-images.githubusercontent.com/6508087/43691574-8cde6b5a-98ec-11e8-9913-50c2d1fe6b08.png)

I have also tried to add the IP in the host.ics and that did not work 

![bf2142hosts](https://user-images.githubusercontent.com/6508087/43691690-232f4e5c-98ee-11e8-89b3-57a4d793b8eb.png)

I have windows 10

here is a net stat output

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:135            X370-PRO:0             LISTENING
  TCP    0.0.0.0:445            X370-PRO:0             LISTENING
  TCP    0.0.0.0:902            X370-PRO:0             LISTENING
  TCP    0.0.0.0:911            X370-PRO:0             LISTENING
  TCP    0.0.0.0:912            X370-PRO:0             LISTENING
  TCP    0.0.0.0:1801           X370-PRO:0             LISTENING
  TCP    0.0.0.0:2103           X370-PRO:0             LISTENING
  TCP    0.0.0.0:2105           X370-PRO:0             LISTENING
  TCP    0.0.0.0:2107           X370-PRO:0             LISTENING
  TCP    0.0.0.0:5040           X370-PRO:0             LISTENING
  TCP    0.0.0.0:27036          X370-PRO:0             LISTENING
  TCP    0.0.0.0:49664          X370-PRO:0             LISTENING
  TCP    0.0.0.0:49665          X370-PRO:0             LISTENING
  TCP    0.0.0.0:49666          X370-PRO:0             LISTENING
  TCP    0.0.0.0:49667          X370-PRO:0             LISTENING
  TCP    0.0.0.0:49668          X370-PRO:0             LISTENING
  TCP    0.0.0.0:49686          X370-PRO:0             LISTENING
  TCP    0.0.0.0:49699          X370-PRO:0             LISTENING
  TCP    0.0.0.0:49702          X370-PRO:0             LISTENING
  TCP    0.0.0.0:49703          X370-PRO:0             LISTENING
  TCP    127.0.0.1:8307         X370-PRO:0             LISTENING
  TCP    127.0.0.1:9089         X370-PRO:0             LISTENING
  TCP    127.0.0.1:27060        X370-PRO:0             LISTENING
  TCP    192.168.1.2:139        X370-PRO:0             LISTENING
  TCP    192.168.1.2:49677      52.165.175.144:https   ESTABLISHED
  TCP    192.168.1.2:49919      lb-192-30-253-124-iad:https  ESTABLISHED
  TCP    192.168.1.2:49946      151.101.44.133:https   ESTABLISHED
  TCP    192.168.1.2:49955      40.114.95.106:https    ESTABLISHED
  TCP    192.168.1.2:49957      40.114.95.106:https    ESTABLISHED
  TCP    192.168.1.2:49958      a-0001:https           ESTABLISHED
  TCP    192.168.1.2:49959      13.107.42.254:https    ESTABLISHED
  TCP    192.168.1.2:49960      13.107.136.254:https   ESTABLISHED
  TCP    192.168.1.2:49961      13.107.6.254:https     ESTABLISHED
  TCP    192.168.1.2:49962      204.79.197.222:https   ESTABLISHED
  TCP    192.168.1.2:49967      13.107.246.254:https   ESTABLISHED
  TCP    192.168.1.2:49968      13.107.51.254:https    ESTABLISHED
  TCP    192.168.1.2:49969      bf2142-pc:http         SYN_SENT
  TCP    192.168.1.2:49970      72.3.184.153:17475     SYN_SENT
  TCP    192.168.47.1:139       X370-PRO:0             LISTENING
  TCP    192.168.127.1:139      X370-PRO:0             LISTENING
  TCP    [::]:135               X370-PRO:0             LISTENING
  TCP    [::]:445               X370-PRO:0             LISTENING
  TCP    [::]:911               X370-PRO:0             LISTENING
  TCP    [::]:1801              X370-PRO:0             LISTENING
  TCP    [::]:2103              X370-PRO:0             LISTENING
  TCP    [::]:2105              X370-PRO:0             LISTENING
  TCP    [::]:2107              X370-PRO:0             LISTENING
  TCP    [::]:49664             X370-PRO:0             LISTENING
  TCP    [::]:49665             X370-PRO:0             LISTENING
  TCP    [::]:49666             X370-PRO:0             LISTENING
  TCP    [::]:49667             X370-PRO:0             LISTENING
  TCP    [::]:49668             X370-PRO:0             LISTENING
  TCP    [::]:49686             X370-PRO:0             LISTENING
  TCP    [::]:49699             X370-PRO:0             LISTENING
  TCP    [::]:49703             X370-PRO:0             LISTENING
  TCP    [::1]:8307             X370-PRO:0             LISTENING
  TCP    [::1]:9089             X370-PRO:0             LISTENING
  UDP    0.0.0.0:500            *:*
  UDP    0.0.0.0:3702           *:*
  UDP    0.0.0.0:3702           *:*
  UDP    0.0.0.0:4500           *:*
  UDP    0.0.0.0:5050           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5355           *:*
  UDP    0.0.0.0:27036          *:*
  UDP    0.0.0.0:59086          *:*
  UDP    0.0.0.0:62689          *:*
  UDP    127.0.0.1:1900         *:*
  UDP    127.0.0.1:60820        *:*
  UDP    127.0.0.1:62247        *:*
  UDP    192.168.1.2:137        *:*
  UDP    192.168.1.2:138        *:*
  UDP    192.168.1.2:1900       *:*
  UDP    192.168.1.2:62244      *:*
  UDP    192.168.47.1:137       *:*
  UDP    192.168.47.1:138       *:*
  UDP    192.168.47.1:1900      *:*
  UDP    192.168.47.1:62245     *:*
  UDP    192.168.127.1:137      *:*
  UDP    192.168.127.1:138      *:*
  UDP    192.168.127.1:1900     *:*
  UDP    192.168.127.1:62246    *:*
  UDP    [::]:500               *:*
  UDP    [::]:3702              *:*
  UDP    [::]:3702              *:*
  UDP    [::]:4500              *:*
  UDP    [::]:5353              *:*
  UDP    [::]:5353              *:*
  UDP    [::]:5353              *:*
  UDP    [::]:5353              *:*
  UDP    [::]:5355              *:*
  UDP    [::]:27036             *:*
  UDP    [::]:62690             *:*
  UDP    [::1]:1900             *:*
  UDP    [::1]:62243            *:*
  UDP    [fe80::8033:be5e:83b2:395%11]:1900  *:*
  UDP    [fe80::8033:be5e:83b2:395%11]:62241  *:*
  UDP    [fe80::988e:750c:1484:36a4%10]:1900  *:*
  UDP    [fe80::988e:750c:1484:36a4%10]:62240  *:*
  UDP    [fe80::b934:a3f5:4c99:3fc1%3]:1900  *:*
  UDP    [fe80::b934:a3f5:4c99:3fc1%3]:62242  *:*

**Comment by EDGECOM666** [comment]
I figured it out I had to change a value in HEX I missed the first time I found it thanks to bug issue #4 
you need to change the following value open HxD

 edit >search > hex value  0301a8c0

![bf2142hex1](https://user-images.githubusercontent.com/6508087/43731130-8bacdf8e-997b-11e8-9497-9ebabae94ccf.png)

Now reverse your IP like this 
  192.168.1.4 = 4.1.168.192 

convert that to hex
  0401a8c0

Enter the converted value into HxD 

![bf2142hex2](https://user-images.githubusercontent.com/6508087/43731389-5a26a156-997c-11e8-916e-1b11baaf8882.png)


here is a website to convert your IP to hex NOTE: when entering the converted value do not add the .(dot in Hxd)

[IP TO HEX CONVERTER](https://www.browserling.com/tools/ip-to-hex)

**Comment by phantomeis** [comment]
Your first screenshot has a typ in it, you see \drivers\etc\bosts, but it must be \rivers\etc\hosts.
none the less i did as you with the cracked file, but my game crashes instantly after starting.

**Comment by EDGECOM666** [comment]
its not a typo if you use any version of windows higher than 7 and you change that to hosts or hosts.ics the exe will instantly crash even if you add the extension because there is no file extension on the host file in the windows directory you can check for yourself if you wish. 

if you are using the 1.51 exe its not needed anyways.

you can copy a hosts.ics from a windows 7 box or crate one in a text editor and place it in the drivers\etc\ folder.
